language: csharp
solution: RecruitmentManagementSystem.sln
sudo: false
install:
  - nuget restore RecruitmentManagementSystem.sln
script:
  - xbuild /p:Configuration=Release RecruitmentManagementSystem.sln
